(function(){'use strict';
const root=document.documentElement, sidebar=document.getElementById('sidebar'), shade=document.getElementById('shade'), menu=document.getElementById('menu');
const dialog=document.getElementById('search-dialog'), query=document.getElementById('search-input'), results=document.getElementById('search-results'), hint=document.getElementById('search-hint');
const sections=[...document.querySelectorAll('main section[id]')], links=[...document.querySelectorAll('.nav-link')];
const searchDocs=sections.map(s=>({id:s.id,title:s.dataset.title||s.querySelector('h2,h1')?.textContent||'',text:(s.querySelector('.prose')||s).innerText.replace(/\s+/g,' ')}));
const notify=(text)=>{const el=document.getElementById('toast');el.textContent=text;el.classList.add('show');clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>el.classList.remove('show'),2400)};
function setMenu(open){sidebar.classList.toggle('open',open);shade.classList.toggle('show',open);menu.setAttribute('aria-expanded',String(open));document.body.style.overflow=open?'hidden':''}
menu.addEventListener('click',()=>setMenu(!sidebar.classList.contains('open')));shade.addEventListener('click',()=>setMenu(false));links.forEach(a=>a.addEventListener('click',()=>setMenu(false)));
const theme=document.getElementById('theme');function updateTheme(){const dark=root.dataset.theme==='dark';theme.setAttribute('aria-label',dark?'切换浅色模式':'切换深色模式');theme.setAttribute('title',dark?'切换浅色模式':'切换深色模式');theme.setAttribute('aria-pressed',String(dark));document.querySelector('meta[name="theme-color"]').content=dark?'#132329':'#f5f4ef'}
theme.addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';try{localStorage.setItem('pet-tech-theme',root.dataset.theme)}catch(e){}updateTheme()});updateTheme();
document.getElementById('print').addEventListener('click',()=>window.print());
async function copyLink(hash){const url=location.protocol==='file:'?'https://dawn2034.github.io/research/pet-tech-2026/'+(hash||''):location.origin+location.pathname+(hash||'');try{await navigator.clipboard.writeText(url);notify('链接已复制')}catch(e){const ta=document.createElement('textarea');ta.value=url;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();const ok=document.execCommand('copy');ta.remove();notify(ok?'链接已复制':'请从地址栏复制链接')}}
document.getElementById('share').addEventListener('click',()=>copyLink(location.hash));document.querySelectorAll('.link-btn').forEach(b=>b.addEventListener('click',()=>copyLink('#'+b.dataset.target)));
const topBtn=document.getElementById('back-top');topBtn.addEventListener('click',()=>window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'}));
let ticking=false;function track(){ticking=false;const y=window.scrollY,total=document.documentElement.scrollHeight-window.innerHeight,pct=total>0?Math.min(100,Math.max(0,Math.round(y/total*100))):100;document.getElementById('progress-bar').style.width=pct+'%';document.getElementById('reading-percent').textContent=pct+'%';topBtn.classList.toggle('show',y>600);let active=sections[0]?.id;for(const s of sections){if(s.getBoundingClientRect().top<=150)active=s.id;else break}for(const a of links){const selected=a.hash==='#'+active;a.classList.toggle('active',selected);if(selected)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')}}window.addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(track);ticking=true}},{passive:true});window.addEventListener('resize',()=>{if(innerWidth>780)setMenu(false);track()});track();
function openSearch(){setMenu(false);dialog.showModal();query.focus();runSearch()}document.getElementById('search-open').addEventListener('click',openSearch);document.getElementById('search-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
function appendHighlight(el,text,term){if(!term){el.textContent=text;return}let pos=0,index=0;const lower=text.toLowerCase(),key=term.toLowerCase();while((index=lower.indexOf(key,pos))!==-1){el.append(document.createTextNode(text.slice(pos,index)));const mark=document.createElement('mark');mark.textContent=text.slice(index,index+term.length);el.append(mark);pos=index+term.length}el.append(document.createTextNode(text.slice(pos)))}
function runSearch(){const term=query.value.trim();results.replaceChildren();const found=searchDocs.filter(d=>!term||(d.title+' '+d.text).toLowerCase().includes(term.toLowerCase()));hint.textContent=term?'找到 '+found.length+' 个匹配章节':'按关键词搜索全文，例如 PETKIT、保险、61.9%';for(const d of found){const a=document.createElement('a');a.className='search-result';a.href='#'+d.id;const title=document.createElement('strong');appendHighlight(title,d.title,term);const p=document.createElement('p'),idx=term?d.text.toLowerCase().indexOf(term.toLowerCase()):0;const start=Math.max(0,idx-35),snippet=(start?'…':'')+d.text.slice(start,start+115)+(d.text.length>start+115?'…':'');appendHighlight(p,snippet,term);a.append(title,p);a.addEventListener('click',()=>{dialog.close();const target=document.getElementById(d.id);target.setAttribute('tabindex','-1');setTimeout(()=>target.focus({preventScroll:true}),60)});results.append(a)}if(!found.length){const p=document.createElement('p');p.className='empty-search';p.textContent='没有找到匹配章节，换一个关键词试试。';results.append(p)}}query.addEventListener('input',runSearch);query.addEventListener('keydown',e=>{if(e.key==='Enter'){const a=results.querySelector('a');if(a){e.preventDefault();a.click()}}if(e.key==='ArrowDown'){e.preventDefault();results.querySelector('a')?.focus()}});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();dialog.open?dialog.close():openSearch()}if(e.key==='Escape')setMenu(false)});
const companyInput=document.getElementById('company-search');if(companyInput){const rows=[...document.querySelectorAll('#s11 tbody tr')];companyInput.addEventListener('input',()=>{const q=companyInput.value.trim().toLowerCase();let n=0;for(const row of rows){row.hidden=q&&!row.textContent.toLowerCase().includes(q);if(!row.hidden)n++}document.getElementById('company-count').textContent=n+' / '+rows.length;document.getElementById('company-empty').hidden=n>0;requestAnimationFrame(track)})}
window.addEventListener('afterprint',track);
})();
